-- =============================================================================
-- Esquema PostgreSQL portable (Railway / Postgres estándar)
-- Alineado con app/models/all_models.py
-- =============================================================================
-- DIFERENCIAS vs esquema histórico en Supabase (documentadas, no inventadas):
-- 1) users.id_user_supabase NO referencia auth.users (schema auth no existe fuera
--    de Supabase). En Supabase esa FK y el trigger de perfil pueden existir.
-- 2) especialidades.numero es TEXT en el modelo actual (antes era INTEGER en el
--    SQL original del proyecto).
-- 3) roles de users incluyen 'Marketing' (Admin | User | Marketing).
-- 4) No se incluyen funciones/triggers de updated_at ni de auth (opcionales).
-- =============================================================================

CREATE TABLE IF NOT EXISTS especialidades (
    id_especialidad BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    numero VARCHAR,
    code VARCHAR(100),
    estado VARCHAR(20) DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Inactivo')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
    id_user BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user_supabase UUID,
    nombre_usuario VARCHAR(100) NOT NULL,
    rol VARCHAR(20) DEFAULT 'User' CHECK (rol IN ('User', 'Admin', 'Marketing')),
    estado VARCHAR(20) DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Inactivo')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS doctores (
    id_doctor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    estado VARCHAR(20) DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Inactivo')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS promociones (
    id_promocion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    fecha_inicio DATE,
    fecha_fin DATE,
    estado VARCHAR(20) DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Inactivo')),
    promocion_img TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT chk_fechas CHECK (fecha_fin > fecha_inicio)
);

CREATE TABLE IF NOT EXISTS informes (
    id_informe BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,
    informe_img TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS doctor_especialidad (
    id_doctor BIGINT REFERENCES doctores(id_doctor) ON DELETE CASCADE,
    id_especialidad BIGINT REFERENCES especialidades(id_especialidad) ON DELETE CASCADE,
    PRIMARY KEY (id_doctor, id_especialidad)
);

CREATE TABLE IF NOT EXISTS promocion_especialidad (
    id_promocion BIGINT REFERENCES promociones(id_promocion) ON DELETE CASCADE,
    id_especialidad BIGINT REFERENCES especialidades(id_especialidad) ON DELETE CASCADE,
    PRIMARY KEY (id_promocion, id_especialidad)
);

CREATE TABLE IF NOT EXISTS informe_especialidad (
    id_informe BIGINT REFERENCES informes(id_informe) ON DELETE CASCADE,
    id_especialidad BIGINT REFERENCES especialidades(id_especialidad) ON DELETE CASCADE,
    PRIMARY KEY (id_informe, id_especialidad)
);

CREATE TABLE IF NOT EXISTS horario (
    id_horario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_doctor BIGINT REFERENCES doctores(id_doctor) ON DELETE CASCADE,
    dia_semana VARCHAR(50) NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    estado VARCHAR(20) DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Inactivo')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT chk_horas CHECK (hora_fin > hora_inicio)
);

CREATE INDEX IF NOT EXISTS idx_doc_esp_doctor ON doctor_especialidad(id_doctor);
CREATE INDEX IF NOT EXISTS idx_doc_esp_especialidad ON doctor_especialidad(id_especialidad);
CREATE INDEX IF NOT EXISTS idx_promo_esp_promocion ON promocion_especialidad(id_promocion);
CREATE INDEX IF NOT EXISTS idx_promo_esp_especialidad ON promocion_especialidad(id_especialidad);
CREATE INDEX IF NOT EXISTS idx_inf_esp_informe ON informe_especialidad(id_informe);
CREATE INDEX IF NOT EXISTS idx_inf_esp_especialidad ON informe_especialidad(id_especialidad);
CREATE INDEX IF NOT EXISTS idx_horario_doctor ON horario(id_doctor);
